name: evapp
description: "Evapp"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.5
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  firebase_messaging: ^14.9.2
  firebase_analytics: ^10.10.5
  image_picker: ^1.1.1
  lottie: ^3.1.2
  intl: ^0.19.0
  http: ^1.2.1
  connectivity_plus: ^6.0.3
  #geolocator: ^12.0.0
  #google_maps_flutter: ^2.6.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/logo/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
